### ISSUE TITLE
Fails to build with PDL 2.059

### ISSUE THREAD

**Issue by sebastic** [moocow-the-bovine/PDL-VectorValued#1]
PDL-VectorValues fails to build with PDL 2.059:
```
make[2]: Entering directory '/build/libpdl-vectorvalued-perl-1.0.13/Utils'
cp VectorValued.pm blib/lib/PDL/VectorValued.pm
"/usr/bin/perl" "-I/usr/lib/x86_64-linux-gnu/perl5/5.32" "-MPDL::PP=PDL::VectorValued::Utils,PDL::VectorValued::Utils,Utils,," utils.pd
Running Mkbootstrap for Utils ()
chmod 644 "Utils.bs"
Undefined subroutine &PDL::Types::typesrtkeys called at ../VectorValued/Dev.pm line 96.
Compilation failed in require at utils.pd line 11.
make[2]: *** [Makefile:897: Utils.pm] Error 255
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/build/libpdl-vectorvalued-perl-1.0.13/Utils'
```

**Comment by sebastic** [comment]
@mohawk2, this was not fixed with PDL 2.061 like PDL-NetCDF & PDL-Stats.

Do you have any suggestions for an appropriate fix?

**Comment by moocow-the-bovine** [comment]
@sebastic thanks for the report; should be fixed by 277a66704b83c79f4605f50fec5f787c82b5e3f5 , now on CPAN as v1.0.14.

**Comment by mohawk2** [comment]
Sorry to be a bit late to this. Nice work, @moocow-the-bovine!

**Comment by mohawk2** [comment]
If this is fixed, should the issue be closed? :-)
